Initial commit of masterpiece creator disco diffusion app
Lightning-AI-Dev/Awesome-Lightning pull request #18
Opened 2022-10-22 11:30 UTC by KogayIrina

# Before submitting

- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [ ] Did you read the [contributor guideline](https://github.com/Lightning-AI/pytorch-lightning/blob/main/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you pin the dependency versions?
- [x] Does this work locally and on cloud?
- [ ] Did you add instructions to run the App?
- [ ] Did you write any new necessary tests?

## What does this PR do?

Initial commit of the masterpiece creator disco diffusion lightning app.

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?

Make sure you had fun coding 🙃

2022-10-22 21:12 UTC, aniketmaurya requested changes
Great app idea! Can we add the source code in the project rather than the git submodule, please?

2022-10-23 08:55 UTC, KogayIrina commented
Hi, @aniketmaurya 
Thank you for the comment. I added the source code to this PR, can you check it, please?

2022-10-23 08:59 UTC, KogayIrina commented
By the way, I found that the link to the contributor guideline from the PR template is broken.

![image](https://user-images.githubusercontent.com/63745301/197383548-81f63fb3-1326-4754-b872-a531d88f77b2.png)


 @aniketmaurya

2022-10-24 10:51 UTC, aniketmaurya commented on src/masterpiece-creator-app/app.py
> +app = L.LightningApp(MasterpieceCreator(cloud_compute=L.CloudCompute("gpu")))
the app is not running locally. We need to wrap the `MasterpieceCreator` work inside a `LightningFlow` object.

```python
class RootFlow(L.LightningFlow):
  def __init__(self):
     super().__init__()
     self.work = MasterpieceCreator(cloud_compute=L.CloudCompute("gpu"))
  
  def run(self, *args, **kwargs) -> None:
     self.work.run()
  
  def configure_layout(self):
     return {"name": "Art", "content": self.work.url}


app = L.LightningApp(RootFlow())
```

2022-10-24 11:18 UTC, aniketmaurya approved these changes
LGTM

2022-10-24 11:18 UTC, merged